// Seed exemplar for the Target-o-meter acceptance suite.
//
// Generated by /10x-e2e (ui-chores). Models the conventions every generated
// acceptance spec should follow. The globalSetup boots the full stack (Django
// runserver + Vite + qcluster) with DEV_AUTH_BYPASS_SUB set, so /v1/me returns
// 200 and the SPA mounts AppShell on the first page load — no storageState /
// UI login is needed; the dev-bypass cookie session covers auth. Match this
// in every generated spec:
//
//   - import { test, expect } from '@playwright/test';
//   - role/label/text locators only (never CSS selectors).
//   - page.goto('/<route>') — the dev bypass makes it authed.
//   - page.setViewportSize() for viewport-dependent behavior (the 760px
//     breakpoint is load-bearing for the mobile camera button).
//   - toBeVisible / toHaveURL / toHaveAttribute as web-first assertions — no
//     waitForTimeout.
//   - name the test after the risk it protects.
import { test, expect } from '@playwright/test';

test.describe('Seed exemplar', () => {
  test('the SPA boots authed at /dashboard (dev bypass)', async ({ page }) => {
    await page.goto('/dashboard');
    await expect(page.getByRole('banner')).toBeVisible();
    await expect(page.getByRole('navigation', { name: /main navigation/i })).toBeVisible();
  });
});
