# Generated by Django 6.0.5 on 2026-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_set_nick",
            field=models.BooleanField(default=False),
        ),
    ]
