# Generated by Django 6.0.5 on 2026-07-29 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_has_set_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('duration_kind', models.CharField(choices=[('1h', '1 hour'), ('1d', '1 day'), ('7d', '7 days'), ('30d', '30 days')], max_length=8)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('banned_until', models.DateTimeField()),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_ban',
                'ordering': ['-banned_at'],
            },
        ),
    ]
