"""
Django settings for target_o_meter project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean env var (``"True"``/``"1"``/``"false"``/…)."""
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-0n%b*1&a_*5va-)s1tv8e+98yzsb=o*f!7w%h#puwwsjz6dlq6")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",") if os.environ.get("ALLOWED_HOSTS") else []


# ---------------------------------------------------------------------------
# Identity & auth env vars (F-01). UPPER_SNAKE + os.environ.get convention.
# All secrets default to empty string so an unset prod env fails closed.
# ---------------------------------------------------------------------------

# Auth0 OIDC client (BFF / Authorization Code + PKCE). Empty in dev — the
# dev-bypass middleware (Phase 4) makes Auth0 optional locally.
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID", "")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET", "")
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN", "")

# The single source of truth for the Owner role. ``User.role`` derives Owner
# by comparing ``self.sub == OWNER_SUB_ID`` (research §7 — never persisted).
# Empty → fails closed (no one is Owner; W001 warns in prod).
OWNER_SUB_ID = os.environ.get("OWNER_SUB_ID", "")

# Dev-only auth bypass: when set AND DEBUG=True, every request is authenticated
# as this sub's user (Phase 4 middleware). Setting it equal to OWNER_SUB_ID
# impersonates Owner locally. target_o_meter.E001 refuses to boot if this is
# set while DEBUG=False (Phase 2.4 production guard).
DEV_AUTH_BYPASS_SUB = os.environ.get("DEV_AUTH_BYPASS_SUB", "")

# Seeded dev admin (Django admin login). Dev-only — never set in prod.
# ``create_superuser`` (Phase 1.2) requires a usable password here.
DEV_ADMIN_SUB = os.environ.get("DEV_ADMIN_SUB", "")
DEV_ADMIN_NICK = os.environ.get("DEV_ADMIN_NICK", "dev-admin")
DEV_ADMIN_PASSWORD = os.environ.get("DEV_ADMIN_PASSWORD", "")

# Cookie hardening toggle. False in dev (no HTTPS on localhost); True in prod.
# Session + CSRF cookie SECURE flags both follow this single switch.
SECURE_COOKIES = _env_bool("SECURE_COOKIES", False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Async task queue (AGENTS.md §2: django-q2 with SQLite broker via ORM
    # broker — task records live in the Django DB, which is SQLite here).
    'django_q',
    # Bounded Contexts (DDD). Prefixed with `src.` to match the import-linter
    # root package (AGENTS.md \u00a76.1) and the BFF import convention (AGENTS.md \u00a76.2).
    'src.domains.core',
    'src.domains.identity',
    'src.domains.vision',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Dev-only auth bypass (Phase 4). MUST sit immediately after
    # AuthenticationMiddleware so it overwrites the AnonymousUser it set.
    # Self-gates on DEBUG=False (plan-review F2 serving-layer guard); E001 is
    # the boot-layer guard.
    'src.target_o_meter.dev_auth_bypass.DevAuthBypassMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.target_o_meter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.target_o_meter.wsgi.application'

# Custom user model — identity domain owns the zero-email anchor (research §7).
# Must be set BEFORE the first identity migration runs (Critical Implementation
# Details). App **label** (not dotted path) — matches apps.py:5.
AUTH_USER_MODEL = "identity.User"


# ---------------------------------------------------------------------------
# Session & CSRF cookie hardening (research §5 — BFF pattern).
# ---------------------------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
# SECURE follows the single SECURE_COOKIES toggle (False in dev — no HTTPS on
# localhost; True in prod).
SESSION_COOKIE_SECURE = SECURE_COOKIES
# SameSite=Lax is LOAD-BEARING for the OIDC callback (research §5, Key
# Discoveries): the callback is a cross-site top-level GET navigation. Strict
# would suppress the sessionid cookie on that redirect → Authlib finds no
# nonce in the session → validation fails silently. Do NOT change to Strict.
SESSION_COOKIE_SAMESITE = "Lax"
# 8h bounds token exposure (research §5 — the session is the token store).
SESSION_COOKIE_AGE = 60 * 60 * 8

CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = SECURE_COOKIES
# HttpOnly=False on the CSRF cookie: a future SPA (S-01) must read ``csrftoken``
# to send it on POSTs. django-ninja's NinjaAPI(csrf=True) reads it server-side.
CSRF_COOKIE_HTTPONLY = False


# Register the production-safety system checks (Phase 2.4). Importing this
# module is what makes ``target_o_meter.E001`` / ``W001`` fire at
# ``manage.py check`` time.
from . import checks  # noqa: E402,F401


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', BASE_DIR)) / 'db.sqlite3',
    }
}


# django-q2 — async task queue. AGENTS.md §2: SQLite broker, max 3 concurrent
# workers. The ORM broker stores task records in the Django DB (sqlite here),
# so no external Redis dependency is introduced. The plan §"What We're NOT
# Doing" calls out that the BFF router is a follow-up; this config is just the
# queue plumbing schedule_image_processing uses.
Q_CLUSTER = {
    'name': 'targetometer',
    'workers': 3,            # AGENTS.md §2 cap: Max 3 concurrent processing tasks
    'recycle': 500,
    'timeout': 600,          # CV pipeline can take ~30s/image; allow generous headroom
    'retry': 1200,
    'queue_limit': 50,
    'bulk': 1,               # one image per task — each job is a single task
    'orm': 'default',        # the SQLite-backed broker
    'catch_up': False,       # don't run missed scheduled tasks on restart (none defined)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
