"""
Django settings for target_o_meter project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import logging
import os

# Load .env BEFORE any os.environ.get below reads from it. python-dotenv is a
# declared runtime dep (pyproject.toml); without this call the Django bootstrap
# path (manage.py / wsgi / asgi) never loads .env, so AUTH0_DOMAIN etc. read
# their empty-string defaults and the OAuth client builds a hostless discovery
# URL (the ``Invalid URL 'https:///.well-known/...'`` crash from Phase 5.B).
#
# ``load_dotenv()`` with no path uses ``find_dotenv()``, which walks up from
# THIS FILE's directory (``src/target_o_meter/``) — so it finds ``.env`` at the
# repo root in normal layouts. Override with ``TOM_ENV_FILE=<path>`` to point
# at a non-default location (e.g. a secrets manager's mount in prod).
#
# The return value is captured so a missing/unreadable .env (e.g. a wrong
# ``TOM_ENV_FILE`` mount) surfaces a warning instead of silently failing open
# with empty-string env defaults. Prod is unaffected (the platform injects env
# vars directly; no .env file is expected there, and the no-file case for the
# default ``load_dotenv()`` is intentional — only an explicit ``TOM_ENV_FILE``
# that fails to load is suspicious).
from dotenv import load_dotenv

_env_logger = logging.getLogger("target_o_meter.settings")
_env_file = os.environ.get("TOM_ENV_FILE")
_env_loaded = load_dotenv(_env_file) if _env_file else load_dotenv()
if _env_file and not _env_loaded:
    _env_logger.warning(
        "TOM_ENV_FILE=%s could not be loaded (missing or unreadable); env "
        "vars fall back to their defaults. Check the path / secrets-manager "
        "mount.",
        _env_file,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean env var (``"True"``/``"1"``/``"false"``/…)."""
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# AUTH0_SECRET is the canonical name in .env (Auth0 convention); SECRET_KEY is
# accepted as a Django-conventional alias. Both fall back to the insecure dev
# default so a fresh checkout still runs.
SECRET_KEY = (
    os.environ.get("SECRET_KEY")
    or os.environ.get("AUTH0_SECRET")
    or "django-insecure-0n%b*1&a_*5va-)s1tv8e+98yzsb=o*f!7w%h#puwwsjz6dlq6"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"


def _allowed_hosts(debug: bool) -> list[str]:
    """Build ALLOWED_HOSTS from explicit ALLOWED_HOSTS or derived from APP_BASE_URL.

    APP_BASE_URL is the canonical deploy URL in .env (e.g.
    ``http://localhost:8000``). When ALLOWED_HOSTS is unset, parse the host
    from APP_BASE_URL so a single env var configures both the redirect URI
    base and the host allowlist. Localhost dev → ``["localhost"]``.

    When ``DEBUG=True``, returns ``[]`` so Django's default permissive dev
    behavior is preserved (Django accepts any host in DEBUG when ALLOWED_HOSTS
    is empty — this keeps the live-server test harness, which binds to
    ``127.0.0.1``, working without forcing every test to set ALLOWED_HOSTS).
    The APP_BASE_URL derivation is a prod convenience only.
    """
    explicit = os.environ.get("ALLOWED_HOSTS", "").strip()
    if explicit:
        return [h.strip() for h in explicit.split(",") if h.strip()]
    if debug:
        return []
    base = os.environ.get("APP_BASE_URL", "").strip()
    if base:
        from urllib.parse import urlparse

        host = urlparse(base).hostname
        if host:
            return [host]
    return []


ALLOWED_HOSTS = _allowed_hosts(DEBUG)


# ---------------------------------------------------------------------------
# Identity & auth env vars (F-01). UPPER_SNAKE + os.environ.get convention.
# All secrets default to empty string so an unset prod env fails closed.
# ---------------------------------------------------------------------------

# Auth0 OIDC client (BFF / Authorization Code + PKCE). Empty in dev — the
# dev-bypass middleware (Phase 4) makes Auth0 optional locally.
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID", "")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET", "")
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN", "")

# The single source of truth for the Owner role. ``User.role`` derives Owner
# by comparing ``self.sub == OWNER_SUB_ID`` (research §7 — never persisted).
# Empty → fails closed (no one is Owner; W001 warns in prod).
OWNER_SUB_ID = os.environ.get("OWNER_SUB_ID", "")

# Dev-only auth bypass: when set AND DEBUG=True, every request is authenticated
# as this sub's user (Phase 4 middleware). Setting it equal to OWNER_SUB_ID
# impersonates Owner locally. target_o_meter.E001 refuses to boot if this is
# set while DEBUG=False (Phase 2.4 production guard).
DEV_AUTH_BYPASS_SUB = os.environ.get("DEV_AUTH_BYPASS_SUB", "")

# Seeded dev admin (Django admin login). Dev-only — never set in prod.
# ``create_superuser`` (Phase 1.2) requires a usable password here.
DEV_ADMIN_SUB = os.environ.get("DEV_ADMIN_SUB", "")
DEV_ADMIN_NICK = os.environ.get("DEV_ADMIN_NICK", "dev-admin")
DEV_ADMIN_PASSWORD = os.environ.get("DEV_ADMIN_PASSWORD", "")

# Cookie hardening toggle. False in dev (no HTTPS on localhost); True in prod.
# Session + CSRF cookie SECURE flags both follow this single switch.
SECURE_COOKIES = _env_bool("SECURE_COOKIES", False)


# Application definition

INSTALLED_APPS = [
    # Project-level app (Phase 5): hosts the dev ``runserver`` override that
    # proxies staticfiles misses to Vite, plus the production-safety system
    # checks. MUST come BEFORE ``django.contrib.staticfiles`` — Django resolves
    # management-command name collisions by iterating INSTALLED_APPS in reverse
    # and letting later updates win, so the FIRST app that defines ``runserver``
    # overrides the rest.
    'src.target_o_meter',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Async task queue (AGENTS.md §2: django-q2 with SQLite broker via ORM
    # broker — task records live in the Django DB, which is SQLite here).
    'django_q',
    # S3-compatible object storage (S-02). django-storages ships the
    # ``storages.backends.s3.S3Storage`` backend ``STORAGES['default']`` flips to
    # when ``USE_S3=True`` (Railway Storage Buckets / Tigris in prod, MinIO in
    # docker-compose dev). Required by django-storages even when the FS fallback
    # is active (``USE_S3=False``), so it lives here unconditionally.
    'storages',
    # Bounded Contexts (DDD). Prefixed with `src.` to match the import-linter
    # root package (AGENTS.md \u00a76.1) and the BFF import convention (AGENTS.md \u00a76.2).
    'src.domains.core',
    'src.domains.identity',
    'src.domains.vision',
    # Vite↔Django bridge (S-01 Phase 2). Serves the Vite dev server (HMR) in
    # DEBUG and the hashed bundle (read from dist/manifest.json) in prod via
    # the ``{% vite_* %}`` template tags in templates/base.html.
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Dev-only auth bypass (Phase 4). MUST sit immediately after
    # AuthenticationMiddleware so it overwrites the AnonymousUser it set.
    # Self-gates on DEBUG=False (plan-review F2 serving-layer guard); E001 is
    # the boot-layer guard.
    'src.target_o_meter.dev_auth_bypass.DevAuthBypassMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.target_o_meter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Phase 5: project-level templates dir (F-01 uses Django templates;
        # React lands in S-01). BASE_DIR is ``src/`` (manage.py lives there),
        # so the repo root is BASE_DIR.parent — matches the plan's
        # ``templates/base.html`` path. APP_DIRS stays True for admin.
        'DIRS': [BASE_DIR.parent / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.target_o_meter.wsgi.application'

# Custom user model — identity domain owns the zero-email anchor (research §7).
# Must be set BEFORE the first identity migration runs (Critical Implementation
# Details). App **label** (not dotted path) — matches apps.py:5.
AUTH_USER_MODEL = "identity.User"


# ---------------------------------------------------------------------------
# Session & CSRF cookie hardening (research §5 — BFF pattern).
# ---------------------------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
# SECURE follows the single SECURE_COOKIES toggle (False in dev — no HTTPS on
# localhost; True in prod).
SESSION_COOKIE_SECURE = SECURE_COOKIES
# SameSite=Lax is LOAD-BEARING for the OIDC callback (research §5, Key
# Discoveries): the callback is a cross-site top-level GET navigation. Strict
# would suppress the sessionid cookie on that redirect → Authlib finds no
# nonce in the session → validation fails silently. Do NOT change to Strict.
SESSION_COOKIE_SAMESITE = "Lax"
# 2h bounds the window a banned-but-already-logged-in user can keep operating
# (S-04). The owner chose login-only ban enforcement (no per-request
# middleware), so the session age is the safety bound: a user banned while
# already logged in loses access within ≤2h (next request after expiry → 401 →
# re-login → blocked at the OAuth callback). Previously 8h.
SESSION_COOKIE_AGE = 60 * 60 * 2

CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = SECURE_COOKIES
# HttpOnly=False on the CSRF cookie: a future SPA (S-01) must read ``csrftoken``
# to send it on POSTs. django-ninja's NinjaAPI(csrf=True) reads it server-side.
CSRF_COOKIE_HTTPONLY = False

# Trust Render's TLS-terminating proxy (impl-review F1). Render fronts the app
# with HTTPS and forwards ``X-Forwarded-Proto: https``; without this tuple
# ``request.is_secure()`` returns False in prod, which (a) makes
# ``_safe_next``'s ``require_https=request.is_secure()`` accept same-host
# http:// URLs — a TLS-downgrade vector on the post-login redirect — and
# (b) would silently drop the SECURE flag from cookies if it were derived
# from is_secure(). Gated on SECURE_COOKIES so localhost dev (no HTTPS) is
# unaffected. Do NOT set this without a trusted proxy stripping the header
# upstream — Render does.
if SECURE_COOKIES:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Register the production-safety system checks (Phase 2.4). Importing this
# module is what makes ``target_o_meter.E001`` / ``W001`` fire at
# ``manage.py check`` time.
from . import checks  # noqa: E402,F401


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', BASE_DIR)) / 'db.sqlite3',
    }
}


# django-q2 — async task queue. AGENTS.md §2: SQLite broker, max 3 concurrent
# workers. The ORM broker stores task records in the Django DB (sqlite here),
# so no external Redis dependency is introduced. The plan §"What We're NOT
# Doing" calls out that the BFF router is a follow-up; this config is just the
# queue plumbing schedule_image_processing uses.
Q_CLUSTER = {
    'name': 'targetometer',
    'workers': 3,            # AGENTS.md §2 cap: Max 3 concurrent processing tasks
    'recycle': 500,
    'timeout': 600,          # CV pipeline can take ~30s/image; allow generous headroom
    'retry': 1200,
    'queue_limit': 50,
    'bulk': 1,               # one image per task — each job is a single task
    'orm': 'default',        # the SQLite-backed broker
    'catch_up': False,       # don't run missed scheduled tasks on restart (none defined)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Env-overridable so the live-server test harness can point collectstatic at a
# per-run throwaway dir (avoids collisions across parallel boots). Defaults to
# ``src/staticfiles`` for normal ``collectstatic`` / prod deploys.
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles"))

# Django 6.0 ``STORAGES`` (Phase 5.C). WhiteNoise owns the staticfiles storage
# in prod: it serves hashed bundles from ``STATIC_ROOT`` (populated by
# ``collectstatic``) with gzip/brotli compression + content-hash far-future
# caching. Without this entry, requests for ``/static/assets/main-*.js`` 404 in
# ``DEBUG=False`` — the SPA never mounts and the inlined target.svg vanishes
# (the ``DEBUG=false make dev`` blank-page bug). The middleware registration
# above (``WhiteNoiseMiddleware``) only becomes load-bearing once
# ``collectstatic`` has populated ``STATIC_ROOT`` and the storage backend knows
# how to resolve the hashed manifest. ``whitenoise>=6.12.0`` is a runtime dep.
#
# S-02: the default backend is env-driven via ``USE_S3``. False (default) keeps
# the no-creds host-dev path on ``FileSystemStorage``; True flips to
# django-storages' S3 backend (Railway Storage Buckets / Tigris in prod, MinIO
# in docker-compose dev). The AWS_* vars are read with ``os.environ[...]``
# (not ``.get``) so a missing prod var is a loud ``KeyError`` at boot rather
# than a silent misconfiguration. MinIO-vs-Tigris is controlled by
# ``AWS_S3_ENDPOINT_URL`` (set for MinIO, unset for Tigris).
USE_S3 = _env_bool('USE_S3', False)
_default_backend = (
    'storages.backends.s3.S3Storage' if USE_S3
    else 'django.core.files.storage.FileSystemStorage'
)
STORAGES = {
    'default': {
        'BACKEND': _default_backend,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')  # MinIO only; unset for Tigris
    AWS_S3_ADDRESSING_STYLE = os.environ.get('AWS_S3_ADDRESSING_STYLE', 'auto')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    # S-03 Phase 4: Tigris has no public bucket access, so the SPA's
    # ``<img src={marked_image_url}>`` would 403 on a plain key URL. Presigned
    # (query-string-auth) URLs are time-limited + signed, browser-fetchable under
    # both Tigris (prod) and MinIO (docker-compose dev). 3600s is well over the
    # results-screen view time; django-storages honors these from ``.url(...)``.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600

# S-02 review (impl-review F2): cap multipart upload size so the BFF's
# ``file.read()`` in ``scoring_routes.create_scoring_job`` can't be driven into
# a single multi-MB/multi-GB ``bytes`` allocation per request. Django rejects
# oversized requests with a 413 (RequestDataTooBig) BEFORE the view runs, so
# the upload path never sees them. ``DATA_UPLOAD_MAX_MEMORY_SIZE`` bounds the
# in-memory buffered size (Django spills above this to a temp file via
# ``FILE_UPLOAD_TEMP_DIR``, but the BFF's ``file.read()`` then re-reads the
# whole thing — so this cap also bounds the re-read). 10 MiB comfortably fits
# a real ISSF target photo (typically a few MB) while keeping the per-request
# memory footprint predictable under the §2 3-concurrent-task cap.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MiB; rejects >cap with 413
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # mirror for the disk-spill threshold

# ---------------------------------------------------------------------------
# Vite + django-vite (S-01 Phase 2).
# ---------------------------------------------------------------------------
#
# django-vite 3.1.0 bridges Vite's dev server (HMR) and its hashed production
# build to Django's template layer. When ``dev_mode`` is True, ``{% vite_asset
# %}`` / ``{% vite_react_refresh %}`` emit URLs pointing at the Vite dev server
# (``http://localhost:5173``); when False they resolve hashed files from
# ``dist/manifest.json``. ``dev_mode`` defaults to ``DEBUG`` (so native
# ``make dev`` HMR needs no extra env) but is overridable via
# ``DJANGO_VITE_DEV_MODE`` — see the note on the dict below.
#
# ``manifest_path`` is consulted only when ``dev_mode=False``, but pointing it
# unconditionally is harmless and avoids a dev/prod settings split for S-01's
# scope (plan §"Critical Implementation Details"). The path is absolute and
# lives under ``src/frontend/dist/`` (``BASE_DIR`` == ``src/``).
#
# ``STATICFILES_DIRS`` adds the built bundle so ``collectstatic`` picks it up
# for prod (WhiteNoise serves it). In native dev django-vite proxies to the
# Vite dev server instead, so the entry is unused-but-harmless there; in the
# dev container (``DEBUG=True`` + ``DJANGO_VITE_DEV_MODE=False``) the finders
# serve the baked bundle directly.
FRONTEND_DIR = BASE_DIR / "frontend"

# ``dev_mode`` is decoupled from ``DEBUG`` so the dev-container posture can
# serve the built bundle (manifest mode) while keeping ``DEBUG=True`` for
# backend dev (autoreload, dev-bypass auth, USE_S3 against MinIO).
# ``docker-compose.dev.yml`` runs no Vite dev server (its only services are
# web/worker/minio/create-bucket), so the default ``dev_mode=DEBUG=True`` would
# emit ``http://localhost:5173/...`` with nothing answering → blank page. The
# compose sets ``DJANGO_VITE_DEV_MODE=False`` to force manifest mode. The
# default stays ``DEBUG`` so native ``make dev`` (Django :8000 + Vite :5173,
# HMR) is unchanged. (S-02 impl-review F11.)
DJANGO_VITE = {
    "default": {
        "dev_mode": _env_bool("DJANGO_VITE_DEV_MODE", DEBUG),
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        "manifest_path": FRONTEND_DIR / "dist" / "manifest.json",
    }
}

STATICFILES_DIRS = [
    FRONTEND_DIR / "dist",
]
