# Generated by Django 6.0.5 on 2026-07-23 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('input_path', models.CharField(max_length=512)),
                ('target_type', models.CharField(default='air_pistol', max_length=32)),
                ('caliber_hint', models.CharField(blank=True, max_length=64, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('llm_input_path', models.CharField(blank=True, max_length=512, null=True)),
                ('marked_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('result_json_path', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_scoringjob',
            },
        ),
    ]
