# Generated by Django 6.0.5 on 2026-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
