# Generated by Django 6.0.5 on 2026-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_schedule_stuck_job_reaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringjob',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='weapon_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
