# Generated by Django 6.0.5 on 2026-07-28 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_scoringjob_distance_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(db_index=True)),
                ('source_job', models.UUIDField()),
                ('target_type', models.CharField(max_length=32)),
                ('caliber_hint', models.CharField(blank=True, max_length=64, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('weapon_type', models.CharField(blank=True, max_length=32, null=True)),
                ('holes', models.JSONField()),
                ('score_average', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vision_acceptedresult',
                'unique_together': {('source_job', 'user_uuid')},
            },
        ),
    ]
