# Generated by Django 6.0.5 on 2026-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0005_acceptedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
